name: Test Package
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v3
      # memcached
      - uses: niden/actions-memcached@v7
      # redis
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libmemcached-dev
          python -m pip install --upgrade pip wheel
          pip install -r test-requirements.txt -U
      - name: Lint with flake8
        run: |
          flake8 cachext --show-source --statistics
      - name: Test with pytest
        run: |
          pytest tests --cov cachext
      - name: Coveralls Parallel
        uses: AndreMiras/coveralls-python-action@develop
        with:
          flag-name: "Integration Test - ${{ matrix.python-version }}"
          parallel: true
      - name: Test & publish code coverage
        if: startsWith(github.ref, 'refs/heads/master')
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
  converalls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true